### ISSUE TITLE
Cleaner JSON format for characters in game state

### ISSUE THREAD

**Issue by domob1812** [domob1812/huntercore#12]
Currently, the JSON format for hunters/characters in the game state is messy - the "player state" object contains certain fixed keys like `value` or `color`, but also the individual character states are there directly with keys like `"0"` or `"42"`.  This makes parsing on the client side harder, as one has to check each key either against a hard-coded black list of known fixed keys or for being a valid number formatted as a string in order to determine which character states are present.

We propose to change the format such that all character states are moved to their own subobject `characters`, so that it is easy to enumerate all characters of a player (by just going over all keys of the subobject).

In other words, let's change this:

```
"domob": {
  "color": 2,
  "value": 1.00000000,
  "0": {
    "x": 263,
    "y": 442,
    ...
  },
  "1": {...},
}
```

To this:

```
"domob": {
  "color": 2,
  "value": 1.00000000,
  "characters": {
    "0": {
      "x": 263,
      "y": 442,
      ...
    },
    "1": {...},
  }
}
```

This change requires all front-end software parsing the game state to be updated, but will make the parsing there simpler.  Until all users are updated (e. g., after the next hard fork has taken place), client software can support both formats by checking for the presence of the `characters` field.  In addition, we will update the client version (`version` in `getinfo` output) with this change.

**Comment by RyuMaster** [comment]
We need similar change for:

UniValue jsonPlayers(UniValue::VOBJ);  inside state.cpp line 957;

into

UniValue jsonPlayers(UniValue::VARR);

else it makes impossible to deserialize it easily on client side.

**Comment by domob1812** [comment]
Thanks for your feedback!  Can you please give a more concrete example of what the current JSON looks like that you want to change and how it should look like after the change?  If I understood you correctly, this is about the `players`, similarly to `characters` in the original proposal.  As far as I can see, the players are already in a separate JSON object for themselves.  Why do you think that an array is better?  Since they are key/value pairs (names and state objects), it makes sense to have dictionaries and not an array.

**Comment by RyuMaster** [comment]
Ah, you are correct, those would deserialise into dictionary just fine, so my last comments can be ignored

**Comment by domob1812** [comment]
If you are interested, take a look at my implementation in #13.  I'll merge it if there are no objections or suggestions for further improvements in the next couple of days.
